Add support for Dotenv v3, v4, and v5
junaidbhura/composer-wp-pro-plugins pull request #25
Opened 2020-10-25 19:12 UTC by mcaskill

## Checklist:
- [x] I've read the [Contributing page](https://github.com/junaidbhura/composer-wp-pro-plugins/blob/master/CONTRIBUTING.md).
- [ ] I've created an issue and referenced it here.
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

## Description

Adds support for Dotenv [v5](https://github.com/vlucas/phpdotenv/releases/tag/v5.0.0) while also keeping support for v4 and restoring support for v3.

This allows older projects that might be stuck on an older version of Dotenv to continue to benefit from updates to this Composer plugin.

## How has this been tested?

I'm testing this on a client project that uses Advanced Custom Fields Pro, Gravity Forms, and Polylang Pro.

## Types of changes

#### Added

- Method `Installer::loadDotenv()` to resolve and instantiate the currently available version of the `Dotenv` class.
- Class `AbstractPlugin` as basis for all supported WP plugins. The class provides a `get()` method which serves as a wrapper of `getenv()` that will throw an exception if the requested environment variable is missing.
- Class `MissingEnvException` in case an environment variable is missing.

#### Changed

- WP plugin classes to extend new `AbstractPlugin` and use its `get()` method instead of directly using `getenv()` function.

2020-10-26 06:30 UTC, junaidbhura commented
Thanks @mcaskill ! As always, much appreciated!

Let me take a deeper look and get back to you!

2021-01-17 02:40 UTC, junaidbhura requested changes

2021-01-17 02:40 UTC, junaidbhura commented on Installer.php
> +	 * @return Dotenv|null
@mcaskill Do we need to return anything in this function?

2021-01-17 02:41 UTC, junaidbhura commented
Hey @mcaskill can we limit this PR to just the changes in `Installer.php` ?

I'm looking to do a big refactor of this plugin in the coming months, which will implement an Abstract class, etc.

2021-01-31 17:38 UTC, mcaskill commented
Sorry for the delay and thanks for the feedback.

2021-02-03 06:06 UTC, junaidbhura approved these changes

2021-02-03 06:07 UTC, merged

2021-02-03 06:07 UTC, junaidbhura commented
Thanks @mcaskill really appreciate it as always 👍