Convert EDD plugins from POST to GET
junaidbhura/composer-wp-pro-plugins pull request #40
Opened 2022-12-08 03:14 UTC by jessedyck

## Checklist:
- [x] I've read the [Contributing page](https://github.com/junaidbhura/composer-wp-pro-plugins/blob/master/CONTRIBUTING.md).
- [x] I've created an issue and referenced it here.
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [ ] My code has proper inline documentation.

## Description
Updated EDD plugins, Polylang and WPAll Import, to use GET requests when calling the software licensing API to get the URL of the download. Fixes https://github.com/junaidbhura/composer-wp-pro-plugins/issues/27

## How has this been tested?
✅ Tested installing WP All Import with valid key
🚫 Polylang was not tested - I don't have a license.  Would be great to get that tested prior to merging. 

## Types of changes
* Bug fix

2022-12-09 07:05 UTC, junaidbhura requested changes

2022-12-09 07:05 UTC, junaidbhura commented on plugins/PolylangPro.php
> +		$name = 'Polylang Pro';
@jessedyck Can you undo the changes in this file? Nobody has faced any issues with Polylang, and I don't want to inadvertently cause any issues. WP All Import / Export seem to have a weird EDD implementation.

2022-12-09 07:05 UTC, junaidbhura commented on plugins/WpAiPro.php
> +		} else {
@jessedyck Can we undo this change?

2022-12-09 07:05 UTC, junaidbhura commented on plugins/WpAiPro.php
> +use Exception;
@jessedyck Can we undo this change?

2022-12-09 07:05 UTC, junaidbhura commented on Http.php
> +		$curl_handle = curl_init();
@jessedyck Have you tested this on Windows? I remember facing an issue with the POST request.

2022-12-09 07:05 UTC, junaidbhura commented
Thanks a bunch for your PR, @jessedyck !

Could you please elaborate in what environments / Operating Systems you've tested your changes?

2022-12-15 22:51 UTC, merged

2022-12-15 23:22 UTC, junaidbhura commented
@jessedyck I've merged this PR and made the updates. However, it looks like WP All Import / Export have recently started using Cloudflare, so we're unable to download from the command line at the moment, so I've not created a release just yet!

2022-12-15 23:34 UTC, jessedyck commented
That may explain a change in behaviour I noticed recently; any request would return a download link, regardless of license key. That doesn’t match the expected behaviour from the EDD docs though. I haven’t had a chance to revisit, but perhaps it was cloudflare caching the response then. 

I’ll try to take a peak soon!

2022-12-15 23:39 UTC, junaidbhura commented
That's odd @jessedyck I went ahead and did a release: https://github.com/junaidbhura/composer-wp-pro-plugins/releases/tag/1.5.0 hoping to see if I'd have luck in CI environments, but no dice!

I hope they fix the Cloudflare thing soon.